import Foundation

/// GitHub-style `:shortcode:` emoji, using GitHub's own gemoji list
/// (Resources/emoji.tsv, regenerated by scripts/update-emoji.sh).
public struct EmojiTable {
    /// The table bundled with the app (empty if the resource is missing).
    public static let bundled: EmojiTable = {
        guard let url = Bundle.main.url(forResource: "emoji", withExtension: "tsv"),
              let tsv = try? String(contentsOf: url, encoding: .utf8) else { return EmojiTable(tsv: "") }
        return EmojiTable(tsv: tsv)
    }()

    private let map: [Substring: String]

    public var count: Int { map.count }

    /// Parses `shortcode<TAB>emoji` lines.
    public init(tsv: String) {
        var map: [Substring: String] = [:]
        map.reserveCapacity(2000)
        for line in tsv.split(separator: "\n") {
            guard let tab = line.firstIndex(of: "\t") else { continue }
            map[line[..<tab]] = String(line[line.index(after: tab)...])
        }
        self.map = map
    }

    public subscript(name: Substring) -> String? { map[name] }

    /// Returns `text` with known shortcodes replaced, or nil if nothing changed.
    public func replaceShortcodes(in text: String) -> String? {
        guard text.contains(":") else { return nil }
        var out = ""
        var changed = false
        var rest = text[...]
        while let open = rest.firstIndex(of: ":") {
            let afterOpen = rest.index(after: open)
            guard let close = rest[afterOpen...].firstIndex(of: ":") else { break }
            let name = rest[afterOpen..<close]
            let afterClose = rest.index(after: close)
            // Don't match inside words like "a:b:c" (colons touching letters/digits on the outside).
            let before = open > text.startIndex ? text[text.index(before: open)] : nil
            let after = afterClose < text.endIndex ? text[afterClose] : nil
            let isolated = !(before.map(Self.isAlphanumeric) ?? false) && !(after.map(Self.isAlphanumeric) ?? false)
            if isolated, !name.isEmpty, name.allSatisfy(Self.isShortcodeChar), let emoji = map[name] {
                out += rest[..<open]
                out += emoji
                rest = rest[afterClose...]
                changed = true
            } else {
                // Not a shortcode; the closing colon may start the next one (e.g. "10:30 :tada:").
                out += rest[..<close]
                rest = rest[close...]
            }
        }
        guard changed else { return nil }
        return out + rest
    }

    private static func isAlphanumeric(_ c: Character) -> Bool {
        c.isLetter || c.isNumber
    }

    private static func isShortcodeChar(_ c: Character) -> Bool {
        c.isASCII && (c.isLetter || c.isNumber || c == "_" || c == "+" || c == "-")
    }
}
